[Interface]
Address = 10.8.0.2
DNS = 8.8.8.8
PrivateKey = 2IGMhhCMv498uQbdd6s7fyWfnJ7+qN2dfMXHZAWwSVk=

[Peer]
PublicKey = 4ObAM0rffIX/yrRAO5jF/NlQGNnXZt346vMPBzcLB20=
Endpoint = 209.250.254.111:51820
AllowedIPs = 0.0.0.0/0