"""empty message

Revision ID: 08e28ffbf35b
Revises: 
Create Date: 2020-04-16 23:29:22.073919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e28ffbf35b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unique_id', sa.String(length=255), nullable=False))
    op.drop_constraint('users_token_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['unique_id'])
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_token_key', 'users', ['token'])
    op.drop_column('users', 'unique_id')
    # ### end Alembic commands ###
